### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by roohi66** [AmirKarimi/xcala#2]
سلام
تلاشت برای اشتراک گزاری تجربیاتت واقعا کار بی بدلیلی هست ولی واقعا نبود مستندات ضعف بسیار بزرگی هست در این قسمت.
متاسفانه در کد ها حتی یه کامنت هم ندیدم
کد نویسی با اسکالا نسبتا پیچیده هست و خواندن کد دیگران بیشتر از آن
اگر برای هر فایل لاقل یک پارگراف بنویسی واقعا کمک بسیار زیادی به یوزر خواهی کرد
به شخصه فقط  در دو سه تا از فایل ها را تونستم بفهمم داستان از چه قرار است

**Comment by AmirKarimi** [comment]
You're right we'll try to add documentation, I hope with the help of the community.
